version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mine-detection-db
    environment:
      POSTGRES_DB: mine_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - mine-detection-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mine_detection"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mine-detection-api
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/mine_detection?sslmode=disable
      - SERVER_ADDR=:8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mine-detection-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/devices"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: mine-detection-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - api-gateway
    networks:
      - mine-detection-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  mine-detection-network:
    driver: bridge